#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# The majority of this script is based on Ian Whitlock's "Network Namespaces and Traffic Control"
# <http://gigawhitlocks.com/2014/08/18/network-namespaces.html>.

# The following values are based on Ofcom's research into the bandwidth and latency of 4G and 3G
# networks in the UK <http://stakeholders.ofcom.org.uk/market-data-research/other/telecoms-research/broadband-speeds/mobile-bb-april-15/>.
EGRESS_BANDWIDTH="1.6mbit"
INGRESS_BANDWIDTH="5.9mbit"
ROUND_TRIP_TIME="63.5ms"
ROUND_TRIP_TIME_CORRELATION="6.4ms"

# Execute a command in the gee network namespace.
gee() {
  ip netns exec gee "$@"
}

# Create the gee network namespace.
ip netns add gee

# Create the veth0 and veth1 Virtual Ethernet devices, which will be treated as egress and ingress
# devices respectively.
ip link add veth0 type veth peer name veth1

# Add the ingress device to the network namespace.
ip link set veth1 netns gee

ip addr add 10.1.1.0/31 dev veth0
gee ip addr add 10.1.1.1/31 dev veth1

ip link set veth0 up
gee ip link set veth1 up

# Route traffic from the network namespace via 10.1.1.0 - the egress device.
gee ip route add default via 10.1.1.0

# Enable NAT for traffic from the network namespace.
iptables -t nat -A POSTROUTING -s 10.1.1.0/31 -d 0.0.0.0/0 -j MASQUERADE
sysctl net.ipv4.ip_forward=1 >/dev/null

# Adjust bandwidth and round trip time for the egress interface.
tc qdisc del dev veth0 root 2>/dev/null || true
tc qdisc add dev veth0 root handle 1: htb default 10
tc class add dev veth0 parent 1:1 classid 1:10 htb rate "${EGRESS_BANDWIDTH}" ceil "${EGRESS_BANDWIDTH}"
tc qdisc add dev veth0 parent 1:10 netem delay "${ROUND_TRIP_TIME}" "${ROUND_TRIP_TIME_CORRELATION}" distribution normal

# Adjust bandwidth and round trip time for the ingress interface.
gee tc qdisc del dev veth1 root 2>/dev/null || true
gee tc qdisc add dev veth1 root handle 1: htb default 10
gee tc class add dev veth1 parent 1:1 classid 1:10 htb rate "${INGRESS_BANDWIDTH}" ceil "${INGRESS_BANDWIDTH}"

# Finally, create the gee alias, which, as above, executes a command in the gee network namespace.
echo "alias gee=\"ip netns exec gee\"" >> ~/.bashrc
